name: BigVectorBench-Run

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# Cancel the workflow for the previous commit when the new commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: True

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y libhdf5-dev python3-numpy python3-scipy python3-matplotlib python3-sklearn
      - run: pip3 install --quiet -r requirements.txt
      - run: python -m pytest

  run-benchmarks:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        dataset: [random-xs-32-euclidean, random-xs-32-euclidean-2filter]
        library:
          - bruteforce
          - dummy_algo
          - milvus
          - qdrant
          - weaviate
          - redis
          - elasticsearch
          - sptag
          - pgvector
          # - vearch # Vearch test is disabled temporarily due to disk space constraints.
          # GPU support is not available in the free tier
          # - milvus_gpu
          # - vearch_gpu

    name: ${{ matrix.library }} (${{ matrix.dataset }})

    env:
      LIBRARY: ${{ matrix.library }}
      DATASET: ${{ matrix.dataset }}

    steps:
    - uses: actions/checkout@v4

    - name: Install OS Dependencies
      run: sudo apt-get update && sudo apt-get install -y libhdf5-dev python3-numpy python3-scipy python3-matplotlib python3-sklearn

    - name: Install Project Dependencies
      run: pip3 install --quiet -r requirements.txt

    - name: Build Library Docker Image
      run: python3 install.py --algorithm ${LIBRARY}

      # python3 run.py --docker-tag bigvectorbench-${LIBRARY} --max-n-algorithms 2 --runs 1 --dataset ${DATASET} --run-disabled --batch --timeout 300
      # python3 plot.py --dataset ${DATASET} --output plot-batch.png --batch
    - name: Run the benchmark
      run: |
        python3 run.py --docker-tag bigvectorbench-${LIBRARY} --max-n-algorithms 2 --runs 1 --dataset ${DATASET} --run-disabled --timeout 300
        sudo chmod -R 777 results/
        python3 plot.py --dataset ${DATASET} --output plot.png
        python3 data_export.py --out test.csv
